Algoritmo "enquanto_x_y"





Var
  x, y : inteiro





Inicio
  escreval ("digite dois numeros: ")
  leia (x)
  leia (Y)
  
   enquanto X <> Y faca
   
      se x < y entao
      escreval ("CRESCENTE")
      senao
      escreval ("DECRESCENTE")

      FIMSE


   escreval ("Digite Outros dois numeros: ")
   leia (x)
   leia (y)
   
   fimenquanto






Fimalgoritmo