Algoritmo "pares_consecutivos"






Var

   X, SOMA : INTEIRO



Inicio
soma <- 0

    escreval ("Digite um numero inteiro: ")
    leia (X)
    
     enquanto x <> 0 faca

     se x % 2 <> 0 entao
      x <- x + 1
     fimse
     
     soma <- 5 * x + 20

     escreval ("SOMA = ", SOMA)
     
     escreval ("Digite um numero inteiro: ")
     leia (x)
     
     fimenquanto





Fimalgoritmo