Algoritmo "PROBLEMA DIGITE A SENHA - DIGITAR A SENHA ATE ACERTAR"



Var
   senha : inteiro



Inicio
    escreval ("Digite a senha: ")
    leia (senha)
    
    ENQUANTO SENHA <> 2002 FACA
    escreval ("SENHA INVALIDA! TENTE NOVAMENTE")
    
    LEIA (SENHA)
    
    se senha = 2002 entao
    escreval ("ACESSO PERMITIDO")
    
    
    FIMSE
    FIMENQUANTO





Fimalgoritmo