Algoritmo "Leitura de notas de aluno - ler as notas do aluno e fazer medias"





Var
     X, Y, media : real




Inicio
   Escreva ("Digite a primeira nota: ")
   leia (x)
   
   Escreva ("Digite a segunda nota: ")
   leia (y)
   
   enquanto (x > 0) e (y > 0) faca
   
   media <- (x + y) / 2

   escreval ("MEDIA = ", MEDIA)
   
   Escreva ("Digite a primeira nota: ")
   leia (x)

   Escreva ("Digite a segunda nota: ")
   leia (y)

fimenquanto


Fimalgoritmo